version: '3'
services:
   pypy3:
      container_name: "2_classical_planning"
      image: "2_classical_planning"
      build:
         dockerfile: Dockerfile
         context: .
      volumes:
       - .:/usr/src/app
